<?php

return [
    'brand' => [
        'name' => 'Max Kebab',
        'tagline' => 'Northampton\'s Premium Kebab Experience',
        'logo' => 'assets/images/maxkebab.png',
        'phone' => '+44 7708 449419',
        'phone_display' => '+44 7708 449419',
        'address' => '53 Harborough Rd, Kingsthorpe, Northampton NN2 7SH, United Kingdom',
        'short_address' => 'Kingsthorpe, Northampton',
        'map_url' => 'https://maps.app.goo.gl/8WGTkPchjdBUfpNg8',
        'description' => 'Premium kebab restaurant in Northampton serving authentic grilled favourites, wraps, burgers, sides, salads, dine-in meals, takeaway, and delivery.',
        'keywords' => 'Max Kebab, Northampton kebab, premium kebab restaurant, delivery Northampton, takeaway Northampton, dine-in kebab, fresh grilled food',
        'service_modes' => 'Dine-in, takeaway & delivery',
        'hours_note' => 'Latest opening times are shared on our socials and by phone.',
        'accent' => '#ff5a1f',
        'socials' => [
            ['label' => 'Facebook', 'icon' => 'flaticon-facebook', 'url' => 'https://www.facebook.com/people/Max-K%C3%A9bab/61581423252048/#'],
            ['label' => 'Instagram', 'icon' => 'flaticon-instagram-1', 'url' => 'https://www.instagram.com/max__kebab/'],
            ['label' => 'TikTok', 'text_icon' => 'TT', 'url' => 'https://www.tiktok.com/@max__kebab?_t=ZN-90wsMMdcUJ4&_r=1'],
        ],
        'highlights' => [
            'Premium street-food feel',
            'Fresh ingredients cooked to order',
            'Friendly dine-in, takeaway, and delivery service',
            'Clean preparation and quality-first flavour',
        ],
        'hours' => [
            ['day' => 'Opening updates', 'hours' => 'Latest service times are posted on Facebook, Instagram, and TikTok'],
            ['day' => 'Phone support', 'hours' => '+44 7708 449419'],
            ['day' => 'Delivery', 'hours' => 'Available during service hours'],
            ['day' => 'Collection', 'hours' => '53 Harborough Rd, Kingsthorpe, Northampton'],
        ],
    ],
    'hero_slides' => [
        [
            'headline' => 'Northampton\'s Premium Kebab Experience',
            'subtext' => 'Fresh. Juicy. Authentic.',
            'price' => 'From £8.90',
            'compare_price' => '£11.50',
            'image' => 'assets/images/header-carousel-2.png',
            'slug' => 'signature-doner-wrap',
        ],
        [
            'headline' => 'Chargrilled flavour with clean, modern energy',
            'subtext' => 'Made fresh for dine-in, takeaway, and delivery.',
            'price' => 'Meal deals from £13.90',
            'compare_price' => '£16.90',
            'image' => 'assets/images/header-carousel-1.png',
            'slug' => 'max-smash-burger',
        ],
        [
            'headline' => 'Mixed grills, loaded wraps, and house-made sides',
            'subtext' => 'Premium quality without the fuss.',
            'price' => 'Family feasts from £24.90',
            'compare_price' => '£29.90',
            'image' => 'assets/images/header-carousel-3.png',
            'slug' => 'family-feast-box',
        ],
    ],
    'categories' => [
        ['slug' => 'kebabs', 'name' => 'Kebabs', 'icon' => 'assets/images/menu-1.png'],
        ['slug' => 'burgers', 'name' => 'Burgers', 'icon' => 'assets/images/menu-2.png'],
        ['slug' => 'wings', 'name' => 'Wings', 'icon' => 'assets/images/menu-3.png'],
        ['slug' => 'sides', 'name' => 'Sides', 'icon' => 'assets/images/menu-4.png'],
        ['slug' => 'salads', 'name' => 'Salads', 'icon' => 'assets/images/menu-5.png'],
        ['slug' => 'drinks', 'name' => 'Drinks', 'icon' => 'assets/images/menu-6.png'],
        ['slug' => 'meal-deals', 'name' => 'Meal Deals', 'icon' => 'assets/images/menu-1.png'],
    ],
    'products' => [
        [
            'slug' => 'signature-doner-wrap',
            'sku' => 'MK-001',
            'name' => 'Signature Doner Wrap',
            'category' => 'kebabs',
            'category_name' => 'Kebabs',
            'price' => 8.90,
            'compare_price' => 10.90,
            'image' => 'assets/images/product-7.png',
            'gallery' => ['assets/images/product-7.png'],
            'badge' => 'Bestseller',
            'featured' => true,
            'rating' => 5,
            'review_count' => 38,
            'options' => ['Regular', 'Large'],
            'description' => 'A premium doner wrap layered with shaved meat, crisp salad, pickles, and our house sauce in a warm toasted flatbread.',
            'short_description' => 'Toasted wrap packed with shaved doner, salad, and house sauce.',
        ],
        [
            'slug' => 'mixed-grill-wrap',
            'sku' => 'MK-002',
            'name' => 'Mixed Grill Wrap',
            'category' => 'kebabs',
            'category_name' => 'Kebabs',
            'price' => 11.50,
            'compare_price' => 13.20,
            'image' => 'assets/images/product-7.png',
            'gallery' => ['assets/images/product-7.png'],
            'badge' => 'Chef Pick',
            'featured' => true,
            'rating' => 5,
            'review_count' => 24,
            'options' => ['Regular', 'Meal Deal'],
            'description' => 'Lamb, chicken, and kofte layered together with crunchy salad and a smoky garlic-chilli finish.',
            'short_description' => 'Lamb, chicken, and kofte wrapped with fresh salad.',
        ],
        [
            'slug' => 'chicken-shish-box',
            'sku' => 'MK-003',
            'name' => 'Chicken Shish Box',
            'category' => 'kebabs',
            'category_name' => 'Kebabs',
            'price' => 12.90,
            'compare_price' => 14.50,
            'image' => 'assets/images/max-kebab-squares/chicken-shish-box.jpg',
            'gallery' => ['assets/images/max-kebab-squares/chicken-shish-box.jpg', 'assets/images/combo-4.jpg', 'assets/images/combo-1.jpg'],
            'badge' => 'Fresh Grill',
            'featured' => false,
            'rating' => 4.8,
            'review_count' => 19,
            'options' => ['Rice Box', 'Fries Box'],
            'description' => 'Juicy marinated chicken shish served with your choice of fries or rice, fresh salad, and signature sauces.',
            'short_description' => 'Marinated chicken shish with fries or rice and fresh salad.',
        ],
        [
            'slug' => 'max-smash-burger',
            'sku' => 'MK-004',
            'name' => 'Max Smash Burger',
            'category' => 'burgers',
            'category_name' => 'Burgers',
            'price' => 9.40,
            'compare_price' => 11.40,
            'image' => 'assets/images/product-1.png',
            'gallery' => ['assets/images/product-1.png', 'assets/images/product-2.png', 'assets/images/product-3.png'],
            'badge' => 'House Favourite',
            'featured' => true,
            'rating' => 5,
            'review_count' => 41,
            'options' => ['Single', 'Double'],
            'description' => 'A juicy smashed beef patty with melted cheese, onions, lettuce, pickles, and our bold Max burger sauce.',
            'short_description' => 'Smashed beef burger with cheese, pickles, and Max sauce.',
        ],
        [
            'slug' => 'double-fire-burger',
            'sku' => 'MK-005',
            'name' => 'Double Fire Burger',
            'category' => 'burgers',
            'category_name' => 'Burgers',
            'price' => 10.90,
            'compare_price' => 12.50,
            'image' => 'assets/images/product-2.png',
            'gallery' => ['assets/images/product-2.png', 'assets/images/product-3.png', 'assets/images/service-1.jpg'],
            'badge' => 'Hot',
            'featured' => false,
            'rating' => 4.9,
            'review_count' => 22,
            'options' => ['Single', 'Double'],
            'description' => 'Double beef, grilled jalapenos, flame sauce, and crisp salad for a spicy burger with real attitude.',
            'short_description' => 'Double beef burger finished with jalapenos and flame sauce.',
        ],
        [
            'slug' => 'crispy-chicken-burger',
            'sku' => 'MK-006',
            'name' => 'Crispy Chicken Burger',
            'category' => 'burgers',
            'category_name' => 'Burgers',
            'price' => 8.80,
            'compare_price' => 10.40,
            'image' => 'assets/images/max-kebab-squares/crispy-chicken-burger.jpg',
            'gallery' => ['assets/images/max-kebab-squares/crispy-chicken-burger.jpg', 'assets/images/product-1.png', 'assets/images/product-2.png'],
            'badge' => 'Crunchy',
            'featured' => false,
            'rating' => 4.7,
            'review_count' => 17,
            'options' => ['Regular', 'Meal Deal'],
            'description' => 'Golden crispy chicken stacked with lettuce, pickles, and cool mayo in a glossy seeded bun.',
            'short_description' => 'Golden crispy chicken burger with cool mayo and pickles.',
        ],
        [
            'slug' => 'peri-wings-6',
            'sku' => 'MK-007',
            'name' => 'Peri Wings',
            'category' => 'wings',
            'category_name' => 'Wings',
            'price' => 6.90,
            'compare_price' => 7.90,
            'image' => 'assets/images/max-kebab-squares/peri-wings-6.jpg',
            'gallery' => ['assets/images/max-kebab-squares/peri-wings-6.jpg', 'assets/images/combo-1.jpg', 'assets/images/combo-3.jpg'],
            'badge' => '6 Pieces',
            'featured' => false,
            'rating' => 4.8,
            'review_count' => 16,
            'options' => ['6 Pieces', '12 Pieces'],
            'description' => 'Sticky peri wings with a smoky char, finished with a bright chilli glaze and fresh herbs.',
            'short_description' => 'Sticky peri wings with smoky char and a chilli glaze.',
        ],
        [
            'slug' => 'bbq-wings-12',
            'sku' => 'MK-008',
            'name' => 'BBQ Wings',
            'category' => 'wings',
            'category_name' => 'Wings',
            'price' => 11.90,
            'compare_price' => 13.50,
            'image' => 'assets/images/max-kebab-squares/bbq-wings-12.jpg',
            'gallery' => ['assets/images/max-kebab-squares/bbq-wings-12.jpg', 'assets/images/combo-3.jpg', 'assets/images/combo-1.jpg'],
            'badge' => '12 Pieces',
            'featured' => false,
            'rating' => 4.6,
            'review_count' => 11,
            'options' => ['6 Pieces', '12 Pieces'],
            'description' => 'Slow-coated BBQ wings with a rich glaze and enough crunch to keep every bite satisfying.',
            'short_description' => 'Slow-coated BBQ wings with a sticky sweet glaze.',
        ],
        [
            'slug' => 'skin-on-fries',
            'sku' => 'MK-009',
            'name' => 'Skin-On Fries',
            'category' => 'sides',
            'category_name' => 'Sides',
            'price' => 3.50,
            'compare_price' => 4.20,
            'image' => 'assets/images/max-kebab-squares/skin-on-fries.jpg',
            'gallery' => ['assets/images/max-kebab-squares/skin-on-fries.jpg', 'assets/images/combo-1.jpg'],
            'badge' => 'Classic',
            'featured' => true,
            'rating' => 4.7,
            'review_count' => 28,
            'options' => ['Regular', 'Large'],
            'description' => 'Golden skin-on fries seasoned lightly for the perfect side to wraps, burgers, and wings.',
            'short_description' => 'Golden skin-on fries with a light house seasoning.',
        ],
        [
            'slug' => 'loaded-fries',
            'sku' => 'MK-010',
            'name' => 'Loaded Fries',
            'category' => 'sides',
            'category_name' => 'Sides',
            'price' => 5.90,
            'compare_price' => 6.90,
            'image' => 'assets/images/max-kebab-squares/loaded-fries.jpg',
            'gallery' => ['assets/images/max-kebab-squares/loaded-fries.jpg', 'assets/images/combo-4.jpg', 'assets/images/combo-1.jpg'],
            'badge' => 'Loaded',
            'featured' => false,
            'rating' => 4.9,
            'review_count' => 21,
            'options' => ['Regular', 'Large'],
            'description' => 'Crisp fries topped with sauce, cheese, fresh onions, and a generous hit of doner meat.',
            'short_description' => 'Loaded fries with cheese, sauce, onions, and doner meat.',
        ],
        [
            'slug' => 'house-salad',
            'sku' => 'MK-011',
            'name' => 'House Salad',
            'category' => 'salads',
            'category_name' => 'Salads',
            'price' => 4.20,
            'compare_price' => 4.90,
            'image' => 'assets/images/max-kebab-squares/house-salad.jpg',
            'gallery' => ['assets/images/max-kebab-squares/house-salad.jpg'],
            'badge' => 'Fresh',
            'featured' => false,
            'rating' => 4.5,
            'review_count' => 10,
            'options' => ['Side', 'Large'],
            'description' => 'A crisp mix of lettuce, tomato, cucumber, red onion, and pickled vegetables to brighten every plate.',
            'short_description' => 'Crisp lettuce, tomato, cucumber, onions, and pickled veg.',
        ],
        [
            'slug' => 'grilled-chicken-salad',
            'sku' => 'MK-012',
            'name' => 'Grilled Chicken Salad',
            'category' => 'salads',
            'category_name' => 'Salads',
            'price' => 7.90,
            'compare_price' => 9.20,
            'image' => 'assets/images/max-kebab-squares/grilled-chicken-salad.jpg',
            'gallery' => ['assets/images/max-kebab-squares/grilled-chicken-salad.jpg', 'assets/images/welcome-image-3.jpg'],
            'badge' => 'Lean Choice',
            'featured' => false,
            'rating' => 4.6,
            'review_count' => 13,
            'options' => ['House Dressing', 'Chilli Dressing'],
            'description' => 'Fresh salad topped with chargrilled chicken and a simple dressing that keeps things clean and vibrant.',
            'short_description' => 'Fresh salad finished with chargrilled chicken and house dressing.',
        ],
        [
            'slug' => 'mango-tango-shake',
            'sku' => 'MK-013',
            'name' => 'Mango Tango Shake',
            'category' => 'drinks',
            'category_name' => 'Drinks',
            'price' => 4.50,
            'compare_price' => 5.20,
            'image' => 'assets/images/shake-slider-1.png',
            'gallery' => ['assets/images/shake-slider-1.png', 'assets/images/shake-slider-2.png', 'assets/images/shake-slider-5.png'],
            'badge' => 'Cold',
            'featured' => false,
            'rating' => 4.8,
            'review_count' => 14,
            'options' => ['Regular', 'Large'],
            'description' => 'A creamy mango shake that cools down the heat and pairs beautifully with grilled mains.',
            'short_description' => 'Creamy mango shake made for grilled-food cravings.',
        ],
        [
            'slug' => 'soft-drink-can',
            'sku' => 'MK-014',
            'name' => 'Soft Drink',
            'category' => 'drinks',
            'category_name' => 'Drinks',
            'price' => 1.90,
            'compare_price' => 2.40,
            'image' => 'assets/images/shake-slider-3.png',
            'gallery' => ['assets/images/shake-slider-3.png', 'assets/images/shake-slider-4.png', 'assets/images/shake-slider-5.png'],
            'badge' => 'Chilled',
            'featured' => false,
            'rating' => 4.5,
            'review_count' => 8,
            'options' => ['Cola', 'Fanta', 'Sprite'],
            'description' => 'A chilled canned drink to round out your dine-in, takeaway, or delivery meal.',
            'short_description' => 'Classic chilled drink options served ice cold.',
        ],
        [
            'slug' => 'max-meal-deal',
            'sku' => 'MK-015',
            'name' => 'Max Meal Deal',
            'category' => 'meal-deals',
            'category_name' => 'Meal Deals',
            'price' => 13.90,
            'compare_price' => 16.90,
            'image' => 'assets/images/max-kebab-squares/max-meal-deal.jpg',
            'gallery' => ['assets/images/max-kebab-squares/max-meal-deal.jpg', 'assets/images/combo-1.jpg', 'assets/images/combo-3.jpg'],
            'badge' => 'Value',
            'featured' => true,
            'rating' => 5,
            'review_count' => 30,
            'options' => ['Burger Meal', 'Wrap Meal'],
            'description' => 'Choose a burger or kebab wrap with fries and a drink for a proper Max Kebab meal.',
            'short_description' => 'Burger or wrap with fries and a drink.',
        ],
        [
            'slug' => 'family-feast-box',
            'sku' => 'MK-016',
            'name' => 'Family Feast Box',
            'category' => 'meal-deals',
            'category_name' => 'Meal Deals',
            'price' => 24.90,
            'compare_price' => 29.90,
            'image' => 'assets/images/max-kebab-squares/family-feast-box.jpg',
            'gallery' => ['assets/images/max-kebab-squares/family-feast-box.jpg', 'assets/images/combo-4.jpg', 'assets/images/combo-3.jpg'],
            'badge' => 'Share Box',
            'featured' => true,
            'rating' => 5,
            'review_count' => 18,
            'options' => ['2 People', '4 People'],
            'description' => 'A generous share box with mixed grilled favourites, fries, dips, and fresh salad for the table.',
            'short_description' => 'Mixed grilled favourites, fries, dips, and salad for sharing.',
        ],
    ],
    'reviews' => [
        [
            'name' => 'Aisha Rahman',
            'designation' => 'Local diner',
            'image' => 'assets/images/client-1.jpg',
            'rating' => 5,
            'quote' => 'Fresh, authentic, and packed with flavour. The staff were genuinely friendly and the whole place felt clean and looked after.',
        ],
        [
            'name' => 'Daniel Moore',
            'designation' => 'Takeaway regular',
            'image' => 'assets/images/client-2.jpg',
            'rating' => 5,
            'quote' => 'The meat tasted properly grilled and the salad was crisp. It feels more premium than the usual late-night takeaway spots.',
        ],
        [
            'name' => 'Sophia Clarke',
            'designation' => 'Northampton foodie',
            'image' => 'assets/images/client-3.jpg',
            'rating' => 5,
            'quote' => 'Delicious food, clean presentation, and a friendly atmosphere. Max Kebab gets the balance right between street-food energy and quality.',
        ],
    ],
];
