<?php

$shop = 'assets/images/shop/';

return [
    'categories' => [
        ['slug' => 'kebabs', 'name' => 'Kebabs', 'icon' => 'assets/images/menu-3.png', 'description' => 'Freshly grilled wraps and premium house kebabs.'],
        ['slug' => 'gozleme', 'name' => 'Gözleme', 'icon' => 'assets/images/menu-2.png', 'description' => 'Toasted Turkish flatbreads with savoury fillings.'],
        ['slug' => 'pockets', 'name' => 'Pockets', 'icon' => 'assets/images/menu-3.png', 'description' => 'Warm pocket breads packed with house fillings.'],
        ['slug' => 'sides', 'name' => 'Sides', 'icon' => 'assets/images/menu-6.png', 'description' => 'Crispy sides and quick add-ons.'],
        ['slug' => 'wings', 'name' => 'Chicken Wings', 'icon' => 'assets/images/menu-2.png', 'description' => 'Juicy wings available in two sizes.'],
        ['slug' => 'burgers', 'name' => 'Burgers', 'icon' => 'assets/images/menu-1.png', 'description' => 'Fresh burgers built for real appetite.'],
        ['slug' => 'box-meals', 'name' => 'Box Meals', 'icon' => 'assets/images/menu-6.png', 'description' => 'Hot boxes and quick specials from the grill.'],
        ['slug' => 'salads', 'name' => 'Salads', 'icon' => 'assets/images/menu-5.png', 'description' => 'Fresh salads for lighter bites.'],
        ['slug' => 'meal-deals', 'name' => 'Meal Deals', 'icon' => 'assets/images/menu-4.png', 'description' => 'Proper value combos with fries and drinks.'],
        ['slug' => 'drinks', 'name' => 'Drinks', 'icon' => 'assets/images/menu-4.png', 'description' => 'Cold soft drinks and water.'],
    ],
    'products' => [
        [
            'slug' => 'chicken-kebab',
            'sku' => 'MK-101',
            'name' => 'Chicken Kebab',
            'category' => 'kebabs',
            'price' => 10.00,
            'image' => $shop.'Chicken Kebab.png',
            'gallery' => [$shop.'Chicken Kebab.png', $shop.'Lamb Kebab.png'],
            'badge' => 'Bestseller',
            'featured' => true,
            'rating' => 5,
            'review_count' => 48,
            'options' => [
                ['label' => 'Small', 'value' => 'Small', 'price' => 10.00],
                ['label' => 'Large', 'value' => 'Large', 'price' => 12.00],
            ],
            'description' => 'Tender grilled chicken served the Max Kebab way with crisp salad and house sauces in warm bread.',
            'short_description' => 'Freshly grilled chicken kebab with salad and house sauce.',
        ],
        [
            'slug' => 'lamb-kebab',
            'sku' => 'MK-102',
            'name' => 'Lamb Kebab',
            'category' => 'kebabs',
            'price' => 11.00,
            'image' => $shop.'Lamb Kebab.png',
            'gallery' => [$shop.'Lamb Kebab.png', $shop.'Chicken Kebab.png'],
            'badge' => 'Signature',
            'featured' => true,
            'rating' => 5,
            'review_count' => 44,
            'options' => [
                ['label' => 'Small', 'value' => 'Small', 'price' => 11.00],
                ['label' => 'Large', 'value' => 'Large', 'price' => 13.00],
            ],
            'description' => 'Rich lamb kebab layered with fresh salad and bold house flavour for a fuller grilled bite.',
            'short_description' => 'Premium lamb kebab with fresh salad and house sauces.',
        ],
        [
            'slug' => 'mixed-kebab',
            'sku' => 'MK-103',
            'name' => 'Mixed Kebab',
            'category' => 'kebabs',
            'price' => 13.00,
            'image' => $shop.'Lamb Kebab.png',
            'gallery' => [$shop.'Lamb Kebab.png', $shop.'Chicken Kebab.png'],
            'badge' => 'House Favourite',
            'featured' => true,
            'rating' => 5,
            'review_count' => 39,
            'description' => 'A fuller mixed kebab option when you want more than one grilled flavour working together.',
            'short_description' => 'A mixed kebab loaded with layered grilled flavour.',
        ],
        [
            'slug' => 'crispy-kebab',
            'sku' => 'MK-104',
            'name' => 'Crispy Kebab',
            'category' => 'kebabs',
            'price' => 11.50,
            'image' => $shop.'Chicken Kebab.png',
            'gallery' => [$shop.'Chicken Kebab.png', $shop.'Chicken Wings.png'],
            'badge' => 'Crunchy',
            'featured' => false,
            'rating' => 4.8,
            'review_count' => 21,
            'description' => 'A crisp-edged kebab option with fresh salad and Max Kebab house finish.',
            'short_description' => 'Crispy kebab served hot with salad and sauces.',
        ],
        [
            'slug' => 'falafel-kebab',
            'sku' => 'MK-105',
            'name' => 'Falafel Kebab',
            'category' => 'kebabs',
            'price' => 9.00,
            'image' => $shop.'Falafel Bites.png',
            'gallery' => [$shop.'Falafel Bites.png', $shop.'Greek Salad.png'],
            'badge' => 'Veg Pick',
            'featured' => false,
            'rating' => 4.8,
            'review_count' => 18,
            'description' => 'Crisp falafel with fresh salad and sauce for a lighter but satisfying kebab option.',
            'short_description' => 'Falafel kebab with salad and a clean fresh finish.',
        ],
        [
            'slug' => 'fitness-kebab',
            'sku' => 'MK-106',
            'name' => 'Fitness Kebab',
            'category' => 'kebabs',
            'price' => 10.50,
            'image' => $shop.'Chicken Kebab.png',
            'gallery' => [$shop.'Chicken Kebab.png', $shop.'Greek Salad.png'],
            'badge' => 'Fresh Pick',
            'featured' => false,
            'rating' => 4.7,
            'review_count' => 15,
            'description' => 'A cleaner kebab choice focused on grilled flavour and fresh salad balance.',
            'short_description' => 'A lighter kebab built around fresh salad and grilled meat.',
        ],
        [
            'slug' => 'octopus-kebab',
            'sku' => 'MK-107',
            'name' => 'Octopus Kebab',
            'category' => 'kebabs',
            'price' => 15.00,
            'image' => $shop.'Octopus Kebab.png',
            'gallery' => [$shop.'Octopus Kebab.png'],
            'badge' => 'Premium',
            'featured' => false,
            'rating' => 4.9,
            'review_count' => 9,
            'description' => 'A premium seafood-led kebab for guests after something rarer and more distinctive.',
            'short_description' => 'Premium octopus kebab with bold grilled flavour.',
        ],
        [
            'slug' => 'cheese-gozleme',
            'sku' => 'MK-108',
            'name' => 'Cheese Gözleme',
            'category' => 'gozleme',
            'price' => 7.50,
            'image' => $shop.'Cheese Gözleme.png',
            'gallery' => [$shop.'Cheese Gözleme.png'],
            'badge' => 'Cheese Pull',
            'featured' => false,
            'rating' => 4.8,
            'review_count' => 16,
            'description' => 'Toasted gözleme filled with melting cheese for a simple but properly satisfying bite.',
            'short_description' => 'Toasted gözleme folded around warm melted cheese.',
        ],
        [
            'slug' => 'chicken-gozleme',
            'sku' => 'MK-109',
            'name' => 'Chicken Gözleme',
            'category' => 'gozleme',
            'price' => 8.50,
            'image' => $shop.'Chicken Gözleme.png',
            'gallery' => [$shop.'Chicken Gözleme.png'],
            'badge' => 'Toasted',
            'featured' => false,
            'rating' => 4.8,
            'review_count' => 17,
            'description' => 'Toasted gözleme filled with savoury chicken and finished for a hot, crisp fold-over bite.',
            'short_description' => 'Chicken-filled gözleme toasted until crisp and golden.',
        ],
        [
            'slug' => 'max-pocket',
            'sku' => 'MK-110',
            'name' => 'Max Pocket',
            'category' => 'pockets',
            'price' => 9.00,
            'image' => $shop.'Max Pocket.png',
            'gallery' => [$shop.'Max Pocket.png'],
            'badge' => 'House Pocket',
            'featured' => false,
            'rating' => 4.9,
            'review_count' => 20,
            'description' => 'The house pocket option packed with Max Kebab flavour in a softer handheld format.',
            'short_description' => 'House pocket packed with signature Max Kebab flavour.',
        ],
        [
            'slug' => 'chicken-pocket',
            'sku' => 'MK-111',
            'name' => 'Chicken Pocket',
            'category' => 'pockets',
            'price' => 8.50,
            'image' => $shop.'Chicken Pocket.png',
            'gallery' => [$shop.'Chicken Pocket.png'],
            'badge' => 'Light Bite',
            'featured' => false,
            'rating' => 4.7,
            'review_count' => 14,
            'description' => 'Warm pocket bread filled with chicken, fresh salad, and a balanced house finish.',
            'short_description' => 'Warm pocket bread filled with chicken and salad.',
        ],
        [
            'slug' => 'lamb-pocket',
            'sku' => 'MK-112',
            'name' => 'Lamb Pocket',
            'category' => 'pockets',
            'price' => 9.50,
            'image' => $shop.'Lamb Pocket.png',
            'gallery' => [$shop.'Lamb Pocket.png'],
            'badge' => 'Savoury',
            'featured' => false,
            'rating' => 4.8,
            'review_count' => 15,
            'description' => 'A richer lamb pocket with fresh salad and house sauces in soft bread.',
            'short_description' => 'Lamb pocket finished with salad and Max house sauce.',
        ],
        [
            'slug' => 'mozzarella-sticks',
            'sku' => 'MK-113',
            'name' => 'Mozzarella Sticks',
            'category' => 'sides',
            'price' => 6.00,
            'image' => $shop.'Mozzarella Sticks.png',
            'gallery' => [$shop.'Mozzarella Sticks.png'],
            'badge' => 'Crispy',
            'featured' => false,
            'rating' => 4.8,
            'review_count' => 19,
            'description' => 'Golden mozzarella sticks served hot for a classic cheesy side.',
            'short_description' => 'Golden mozzarella sticks with a hot cheesy centre.',
        ],
        [
            'slug' => 'cheese-rolls',
            'sku' => 'MK-114',
            'name' => 'Cheese Rolls',
            'category' => 'sides',
            'price' => 6.00,
            'image' => $shop.'Cheese Rolls.png',
            'gallery' => [$shop.'Cheese Rolls.png'],
            'badge' => 'Golden',
            'featured' => false,
            'rating' => 4.7,
            'review_count' => 13,
            'description' => 'Crisp cheese rolls that work well as a snack or side with a bigger order.',
            'short_description' => 'Golden cheese rolls served hot and crisp.',
        ],
        [
            'slug' => 'falafel-bites',
            'sku' => 'MK-115',
            'name' => 'Falafel Bites',
            'category' => 'sides',
            'price' => 6.00,
            'image' => $shop.'Falafel Bites.png',
            'gallery' => [$shop.'Falafel Bites.png', $shop.'Greek Salad.png'],
            'badge' => 'Plant Based',
            'featured' => false,
            'rating' => 4.7,
            'review_count' => 12,
            'description' => 'Crunchy falafel bites with a fresh herb finish and easy sharing appeal.',
            'short_description' => 'Crunchy falafel bites with a fresh herb finish.',
        ],
        [
            'slug' => 'chips-with-sauce',
            'sku' => 'MK-116',
            'name' => 'Chips with Sauce',
            'category' => 'sides',
            'price' => 4.00,
            'image' => $shop.'Chips with Sauce.png',
            'gallery' => [$shop.'Chips with Sauce.png'],
            'badge' => 'Side Favourite',
            'featured' => false,
            'rating' => 4.7,
            'review_count' => 27,
            'description' => 'Hot chips finished with sauce for the quick side that goes with almost anything.',
            'short_description' => 'Hot chips topped with your choice of sauce.',
        ],
        [
            'slug' => 'chicken-wings',
            'sku' => 'MK-117',
            'name' => 'Chicken Wings',
            'category' => 'wings',
            'price' => 7.99,
            'image' => $shop.'Chicken Wings.png',
            'gallery' => [$shop.'Chicken Wings.png'],
            'badge' => '8 or 12 pcs',
            'featured' => true,
            'rating' => 4.9,
            'review_count' => 31,
            'options' => [
                ['label' => '8 pcs', 'value' => '8 pcs', 'price' => 7.99],
                ['label' => '12 pcs', 'value' => '12 pcs', 'price' => 11.99],
            ],
            'description' => 'Juicy chicken wings available in two sizes when you want a quick share or a bigger portion.',
            'short_description' => 'Chicken wings available as 8 pieces or 12 pieces.',
        ],
        [
            'slug' => 'beef-burger',
            'sku' => 'MK-118',
            'name' => 'Beef Burger',
            'category' => 'burgers',
            'price' => 10.00,
            'image' => $shop.'Beef Burger.png',
            'gallery' => [$shop.'Beef Burger.png'],
            'badge' => 'Grilled',
            'featured' => true,
            'rating' => 4.9,
            'review_count' => 34,
            'options' => [
                ['label' => 'Small', 'value' => 'Small', 'price' => 10.00],
                ['label' => 'Large', 'value' => 'Large', 'price' => 11.50],
            ],
            'description' => 'A proper beef burger served fresh and grilled for a rich, juicy bite.',
            'short_description' => 'Fresh beef burger available in small or large.',
        ],
        [
            'slug' => 'chicken-burger',
            'sku' => 'MK-119',
            'name' => 'Chicken Burger',
            'category' => 'burgers',
            'price' => 9.00,
            'image' => $shop.'Chicken Burger.png',
            'gallery' => [$shop.'Chicken Burger.png'],
            'badge' => 'Classic',
            'featured' => true,
            'rating' => 4.8,
            'review_count' => 23,
            'description' => 'A classic chicken burger built for easy flavour and a clean finish.',
            'short_description' => 'Classic chicken burger served fresh and hot.',
        ],
        [
            'slug' => 'hot-dog',
            'sku' => 'MK-120',
            'name' => 'Hot Dog',
            'category' => 'box-meals',
            'price' => 9.00,
            'image' => $shop.'Hot Dog.png',
            'gallery' => [$shop.'Hot Dog.png'],
            'badge' => 'Street Bite',
            'featured' => false,
            'rating' => 4.6,
            'review_count' => 11,
            'description' => 'A quick hot dog option when you want something easy, hot, and satisfying.',
            'short_description' => 'A quick hot dog served warm with house flavour.',
        ],
        [
            'slug' => 'chicken-box',
            'sku' => 'MK-121',
            'name' => 'Chicken Box',
            'category' => 'box-meals',
            'price' => 11.50,
            'image' => $shop.'Meat + Chips Box.png',
            'gallery' => [$shop.'Meat + Chips Box.png', $shop.'Chicken Kebab.png'],
            'badge' => 'Box Meal',
            'featured' => false,
            'rating' => 4.8,
            'review_count' => 18,
            'description' => 'A fuller chicken box made for takeaway hunger with hot sides and Max Kebab flavour.',
            'short_description' => 'Chicken box meal with hot sides and fresh flavour.',
        ],
        [
            'slug' => 'lamb-box',
            'sku' => 'MK-122',
            'name' => 'Lamb Box',
            'category' => 'box-meals',
            'price' => 13.00,
            'image' => $shop.'Meat + Chips Box.png',
            'gallery' => [$shop.'Meat + Chips Box.png', $shop.'Lamb Kebab.png'],
            'badge' => 'Grill Box',
            'featured' => false,
            'rating' => 4.8,
            'review_count' => 17,
            'description' => 'A richer lamb box built for guests after stronger grilled flavour and a bigger fill.',
            'short_description' => 'Lamb box meal with hot sides and bold grilled flavour.',
        ],
        [
            'slug' => 'meat-chips-box',
            'sku' => 'MK-123',
            'name' => 'Meat + Chips Box',
            'category' => 'box-meals',
            'price' => 7.00,
            'image' => $shop.'Meat + Chips Box.png',
            'gallery' => [$shop.'Meat + Chips Box.png'],
            'badge' => 'Quick Bite',
            'featured' => false,
            'rating' => 4.7,
            'review_count' => 24,
            'description' => 'A simple meat and chips box when you want a quick, filling order without the extra fuss.',
            'short_description' => 'Hot meat and chips in one quick, filling box.',
        ],
        [
            'slug' => 'caesar-salad',
            'sku' => 'MK-124',
            'name' => 'Caesar Salad',
            'category' => 'salads',
            'price' => 12.00,
            'image' => $shop.'Caesar Salad.png',
            'gallery' => [$shop.'Caesar Salad.png'],
            'badge' => 'Fresh',
            'featured' => false,
            'rating' => 4.7,
            'review_count' => 10,
            'description' => 'A fresh Caesar salad built for guests after a cooler, lighter meal option.',
            'short_description' => 'Fresh Caesar salad prepared for a lighter bite.',
        ],
        [
            'slug' => 'greek-salad',
            'sku' => 'MK-125',
            'name' => 'Greek Salad',
            'category' => 'salads',
            'price' => 10.00,
            'image' => $shop.'Greek Salad.png',
            'gallery' => [$shop.'Greek Salad.png'],
            'badge' => 'Light',
            'featured' => false,
            'rating' => 4.7,
            'review_count' => 9,
            'description' => 'A Greek salad option with a clean, bright finish and plenty of freshness.',
            'short_description' => 'Greek salad with a bright, fresh finish.',
        ],
        [
            'slug' => 'chicken-kebab-meal-deal',
            'sku' => 'MK-126',
            'name' => 'Chicken Kebab Meal Deal',
            'category' => 'meal-deals',
            'price' => 13.50,
            'image' => $shop.'Chicken Kebab Meal Deal.png',
            'gallery' => [$shop.'Chicken Kebab Meal Deal.png'],
            'badge' => 'Meal Deal',
            'featured' => true,
            'rating' => 4.9,
            'review_count' => 26,
            'description' => 'Chicken kebab meal deal built to give you the full order in one clean choice.',
            'short_description' => 'Chicken kebab meal deal with fuller value and portion.',
        ],
        [
            'slug' => 'lamb-kebab-meal-deal',
            'sku' => 'MK-127',
            'name' => 'Lamb Kebab Meal Deal',
            'category' => 'meal-deals',
            'price' => 14.50,
            'image' => $shop.'Lamb Kebab Meal Deal.png',
            'gallery' => [$shop.'Lamb Kebab Meal Deal.png'],
            'badge' => 'Meal Deal',
            'featured' => true,
            'rating' => 4.9,
            'review_count' => 22,
            'description' => 'Lamb kebab meal deal with the fuller grilled flavour and proper value built in.',
            'short_description' => 'Lamb kebab meal deal with fries and drink value.',
        ],
        [
            'slug' => 'mixed-kebab-meal-deal',
            'sku' => 'MK-128',
            'name' => 'Mixed Kebab Meal Deal',
            'category' => 'meal-deals',
            'price' => 14.50,
            'image' => $shop.'Mixed Kebab Meal Deal.png',
            'gallery' => [$shop.'Mixed Kebab Meal Deal.png'],
            'badge' => 'Meal Deal',
            'featured' => true,
            'rating' => 5,
            'review_count' => 24,
            'description' => 'A mixed kebab meal deal for guests who want bigger variety in one order.',
            'short_description' => 'Mixed kebab meal deal with fuller flavour and value.',
        ],
        [
            'slug' => 'beef-burger-meal-deal',
            'sku' => 'MK-129',
            'name' => 'Beef Burger Meal Deal',
            'category' => 'meal-deals',
            'price' => 12.50,
            'image' => $shop.'Beef Burger Meal Deal.png',
            'gallery' => [$shop.'Beef Burger Meal Deal.png'],
            'badge' => 'Meal Deal',
            'featured' => false,
            'rating' => 4.8,
            'review_count' => 18,
            'description' => 'A beef burger meal deal that turns a fresh burger into a full order with proper value.',
            'short_description' => 'Beef burger meal deal with fuller value and portion.',
        ],
        [
            'slug' => 'chicken-burger-meal-deal',
            'sku' => 'MK-130',
            'name' => 'Chicken Burger Meal Deal',
            'category' => 'meal-deals',
            'price' => 11.50,
            'image' => $shop.'Chicken Burger Meal Deal.png',
            'gallery' => [$shop.'Chicken Burger Meal Deal.png'],
            'badge' => 'Meal Deal',
            'featured' => false,
            'rating' => 4.8,
            'review_count' => 17,
            'description' => 'Chicken burger meal deal for an easy complete order with the Max Kebab flavour profile.',
            'short_description' => 'Chicken burger meal deal with great everyday value.',
        ],
        [
            'slug' => 'cola',
            'sku' => 'MK-131',
            'name' => 'Cola',
            'category' => 'drinks',
            'price' => 1.50,
            'image' => $shop.'cola.jpg',
            'gallery' => [$shop.'cola.jpg'],
            'rating' => 4.6,
            'review_count' => 8,
            'description' => 'Cold cola to round out your order.',
            'short_description' => 'Cold cola served chilled.',
        ],
        [
            'slug' => 'fanta',
            'sku' => 'MK-132',
            'name' => 'Fanta',
            'category' => 'drinks',
            'price' => 1.50,
            'image' => $shop.'fanta.jpg',
            'gallery' => [$shop.'fanta.jpg'],
            'rating' => 4.6,
            'review_count' => 7,
            'description' => 'Cold Fanta served chilled with your meal.',
            'short_description' => 'Cold Fanta served chilled.',
        ],
        [
            'slug' => 'sprite',
            'sku' => 'MK-133',
            'name' => 'Sprite',
            'category' => 'drinks',
            'price' => 1.50,
            'image' => $shop.'sprite.jpg',
            'gallery' => [$shop.'sprite.jpg'],
            'rating' => 4.6,
            'review_count' => 7,
            'description' => 'Cold Sprite for a crisp, clean soft drink option.',
            'short_description' => 'Cold Sprite served chilled.',
        ],
        [
            'slug' => 'pepsi',
            'sku' => 'MK-134',
            'name' => 'Pepsi',
            'category' => 'drinks',
            'price' => 1.50,
            'image' => $shop.'pepsi.jpg',
            'gallery' => [$shop.'pepsi.jpg'],
            'rating' => 4.6,
            'review_count' => 7,
            'description' => 'Cold Pepsi served with the rest of your order.',
            'short_description' => 'Cold Pepsi served chilled.',
        ],
        [
            'slug' => 'still-water',
            'sku' => 'MK-135',
            'name' => 'Still Water',
            'category' => 'drinks',
            'price' => 1.50,
            'image' => $shop.'still water.jpg',
            'gallery' => [$shop.'still water.jpg'],
            'rating' => 4.6,
            'review_count' => 5,
            'description' => 'Still water for a simple refresh alongside your meal.',
            'short_description' => 'Still water served cold.',
        ],
    ],
];
